### ISSUE TITLE
cards on index page should be fixed size

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/research-software-directory-frontend#40] opened 2018-01-10 14:30 UTC
I just noticed that when you filter such that you have just one card (I had selected only Koninklijke Bibliotheek), the cards get stretched vertically (but not horizontally). I think they should be fixed size.

**Comment by silo-sietse** [comment] 2018-01-10 14:54
This was an older bug that should be fixed by now.
Try to force refresh or open an incognito window to check if the issue is still present.

**Closed** 2018-01-15 12:17 UTC
